name: Build & Deploy Argus (Container Apps)

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login to Azure using the secret you created
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Backend: build from source (Oryx or Dockerfile on the runner) and deploy
      - name: Backend -> Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: rg-argusappenv01
          containerAppName: ca-argus
          acrName: crv5ptzk5iyj3he
          appSourcePath: src/containerapp
          imageToBuild: crv5ptzk5iyj3he.azurecr.io/argus-backend:${{ github.sha }}
          targetPort: 8000        # change if your backend listens on another port
          ingress: external

      # Frontend: build from source and deploy
      - name: Frontend -> Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: rg-argusappenv01
          containerAppName: ca-frontend-h62wtpatkpksy
          acrName: crv5ptzk5iyj3he
          appSourcePath: frontend
          imageToBuild: crv5ptzk5iyj3he.azurecr.io/argus-frontend:${{ github.sha }}
          targetPort: 8080        # change if your frontend listens on another port
          ingress: external
